
theme: "minima"

title: "Wabi blog"
author: "Yehorizon"
description: "It starts with the first step. " 

github_username: "yehorizon"


rss: rss

home_post_limit: 5
comments_repo: yehorizon/yehorizon.github.io

collections:
  personal: 
    output: true

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other

header_pages:
  - about.html
  - posts.html
